### ISSUE TITLE
[QUESTION] How can I make the table height responsive?

### ISSUE THREAD

**Issue by cesalberca** [tannerlinsley/react-table#99]
Hi! I'm loving this library!

I was wondering if I could set the height of the table to match the viewport height, so I have full height table. I'm guessing I would have to play with the value of ´defaultPageSize´ whenever the viewport changes. Any tips on how could I do that? Is there another way?

Thanks!

**Comment by tannerlinsley** [comment]
Try using this css:
```scss
.ReactTable {
  height: 100%; // or a pixel height
  display: flex;
  flex-direction: column;

  .rt-table {
    flex: 100000 0 auto; // or whatever ratio you want
  }
  
  .-pagination,
  .rt-body,
  .rt-tr-group,
  .rt-tr {
    flex: 1 0 auto;
  }
}
```
